# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Pytrain\NEOeditor\Editor_UI\fileTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_templateTab(object):
    def setupUi(self, templateTab):
        templateTab.setObjectName("templateTab")
        templateTab.resize(941, 720)
        self.filetab = QtWidgets.QWidget()
        self.filetab.setObjectName("filetab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filetab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.filetab)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.treeWidget)
        templateTab.addTab(self.filetab, "")
        self.datatab = QtWidgets.QWidget()
        self.datatab.setObjectName("datatab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.datatab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.datatab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        templateTab.addTab(self.datatab, "")

        self.retranslateUi(templateTab)
        templateTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(templateTab)

    def retranslateUi(self, templateTab):
        _translate = QtCore.QCoreApplication.translate
        templateTab.setWindowTitle(_translate("templateTab", "TabWidget"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("templateTab", "属性"))
        self.treeWidget.headerItem().setText(1, _translate("templateTab", "值"))
        self.treeWidget.headerItem().setText(2, _translate("templateTab", "属性注释"))
        templateTab.setTabText(templateTab.indexOf(self.filetab), _translate("templateTab", "文件"))
        templateTab.setTabText(templateTab.indexOf(self.datatab), _translate("templateTab", "数据"))
