# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Pytrain\NEOeditor\Editor_UI\help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help(object):
    def setupUi(self, help):
        help.setObjectName("help")
        help.resize(1017, 652)
        self.verticalLayout = QtWidgets.QVBoxLayout(help)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(help)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listView_key = QtWidgets.QListView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_key.sizePolicy().hasHeightForWidth())
        self.listView_key.setSizePolicy(sizePolicy)
        self.listView_key.setMaximumSize(QtCore.QSize(500, 16777215))
        self.listView_key.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_key.setWordWrap(True)
        self.listView_key.setObjectName("listView_key")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(help)
        self.listView_key.doubleClicked['QModelIndex'].connect(help.show_value) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(help)

    def retranslateUi(self, help):
        _translate = QtCore.QCoreApplication.translate
        help.setWindowTitle(_translate("help", "help"))
